services:
  agent-core:
    image: __IMAGE__
    container_name: phanthy-motus-agent-core-1
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /opt/phanthy-motus/data:/work/resource
      - /opt/phanthy-motus:/opt/phanthy-motus
    environment:
      - DB_PATH=/work/resource/data.db
      - COMPOSE_DIR=/opt/phanthy-motus
      - CONTAINER_NAME=phanthy-motus-agent-core-1
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTDDS_BUILTIN_TRANSPORTS=DEFAULT
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
